name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:

      - name: Set up Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Prepare Host
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y bzr

      - name: Run checks
        run: |
          make ci
